baseURL = 'https://blog.landryzetam.net/'
title = 'Fako Cluster Documentation'
languageCode = 'en-us'

# Language settings
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

# Markup settings
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

[params]
  copyright = "The Fako Cluster Authors"
  privacy_policy = ""

  # Repository configuration (for "Edit this page" links)
  github_repo = "https://github.com/lyzetam/fako-cluster"
  github_branch = "main"
  github_subdir = "docs"

[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 10
    
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/lyzetam/fako-cluster"
    weight = 50
