name: Build & Publish auth-service Image

on:
  push:
    paths:
      - 'apps/auth-service/**'
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:latest
          buildkitd-opts: --debug

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./apps/auth-service
          file: ./apps/auth-service/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          no-cache: true
          pull: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}
          build-args: |
            BUILDKIT_INLINE_CACHE=0